baseURL = "https://www.markdarling.com"
languageCode = "en-gb"
title = "Mark Darling"
copyright = "© Mark Darling"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
[pagination]
  pagerSize = 10

# disqusShortname = "markdarling"

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
#	subtitle = ""
	mainSections = ["blog"]
	showReadingTime = true

# Social Tags (uncommented for basic setup)
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/markdarling"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/markdarling/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/markdarling/"

# Main menu Items
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1
