# Site Settings
baseURL = "https://www.markdarling.com"
languageCode = "en-gb"
title = "Mark Darling"
copyright = "© Mark Darling"

# SEO Settings
enableRobotsTXT = true
canonifyURLs = true
enableGitInfo = true
disableHugoGeneratorInject = true  # Removes Hugo generator meta tag
enableEmoji = true
summaryLength = 200  # Longer summaries for better meta descriptions

[outputs]
home = ["HTML", "RSS", "JSON"]
section = ["HTML", "RSS", "JSON"]  # Enable RSS for sections
taxonomy = ["HTML", "RSS"]  # Enable RSS for taxonomies

[sitemap]
changefreq = "weekly"
priority = 0.5
filename = "sitemap.xml"

# Code Highlight
pygmentsstyle = "monokai"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

# Pagination
[pagination]
  pagerSize = 10

# disqusShortname = "markdarling"

[params]
	mode="light" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
#	subtitle = ""
	mainSections = ["blog"]
	showReadingTime = true
	description = "Digital Innovator and Engineering Leader specializing in mobile development and scalable solutions. Sharing insights on technology, leadership, and building high-performing teams."
	images = ["profile.png"]
	keywords = ["Engineering Leadership", "Mobile Development", "Technology", "Digital Innovation", "Software Engineering", "Tech Leadership", "Mobile Apps", "Software Architecture", "Team Building", "Digital Transformation"]
	author = "Mark Darling"
	defaultAuthor = "Mark Darling"
	locale = "en_GB"
	timeZone = "Europe/London"
	organization = "Gymshark"
	jobTitle = "Engineering Leader"
	twitterCreator = "@markdarling"
	twitterSite = "@markdarling"
	facebookAuthor = "markdarling"
	facebookPublisher = "markdarling"
	linkedinProfile = "markdarling"
	githubProfile = "markdarling"

# Social Media
[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/markdarling"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://twitter.com/markdarling/"

[[params.social]]
name = "Instagram"
icon = "instagram"
url = "https://instagram.com/markdarling/"

[[params.social]]
name = "LinkedIn"
icon = "linkedin"
url = "https://linkedin.com/in/markdarling/"

# Main menu Items
[[menu.main]]
name = "Blog"
url = "/blog"
weight = 1
